# Generated by Django 5.0.6 on 2024-06-30 18:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('감독', '감독'), ('배우', '배우'), ('성우', '성우'), ('연출', '연출'), ('음향', '음향'), ('조명', '조명'), ('의상', '의상'), ('메이크업', '메이크업'), ('아역', '아역'), ('모델', '모델'), ('인플루언서', '인플루언서')], max_length=20)),
                ('profile_photo', models.ImageField(blank=True, upload_to='profile_photo', verbose_name='프로필사진')),
                ('email', models.EmailField(blank=True, max_length=128, verbose_name='이메일')),
                ('one_line', models.CharField(blank=True, max_length=128, verbose_name='한줄소개')),
                ('intro', models.TextField(blank=True, verbose_name='소개글')),
                ('name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='media/', verbose_name='이미지')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolios.portfolio')),
            ],
        ),
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('career_title', models.CharField(max_length=128, verbose_name='작품명')),
                ('career_role', models.CharField(max_length=128, verbose_name='역할')),
                ('career_year', models.DateField(verbose_name='연도')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolios.portfolio')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='제목')),
                ('cast', models.CharField(max_length=128, verbose_name='출연진')),
                ('staff', models.CharField(blank=True, max_length=128, verbose_name='스탭')),
                ('price', models.IntegerField(default=0, verbose_name='가격')),
                ('keyword', models.TextField(blank=True, verbose_name='키워드')),
                ('synopsis', models.TextField(blank=True, verbose_name='시놉시스')),
                ('video', models.FileField(upload_to='media/', verbose_name='동영상')),
                ('likes_user', models.ManyToManyField(blank=True, related_name='likes_user', to=settings.AUTH_USER_MODEL)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolios.portfolio')),
            ],
        ),
    ]
